name: Berlin Service Appointment Monitor

on:
  schedule:
    # Run every 5 minutes during business hours (8 AM to 6 PM, Mon-Fri, Berlin time)
    - cron: '*/5 8-18 * * 1-5'
  workflow_dispatch: # Allow manual triggering

env:
  PYTHONUNBUFFERED: 1

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run appointment monitor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Email notifications (optional)
        NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        # Mobile push notifications (optional - choose one or more)
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
        NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        # Webhook notifications (optional)
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        python src/main.py
        
    - name: Upload logs (if failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs
        path: logs/
        retention-days: 7